steps:
  - imports:
      align: group
  - language_pragmas:
      style: compact_line
      remove_redundant: false

  # Remove trailing whitespace
  - trailing_whitespace: {}

# A common setting is the number of columns (parts of) code will be wrapped
# to. Different steps take this into account. Default: 80.
columns: 80

# Sometimes, language extensions are specified in a cabal file or from the
# command line instead of using language pragmas in the file. stylish-haskell
# needs to be aware of these, so it can parse the file correctly.
#
# No language extensions are enabled by default.
language_extensions:
  -   DeriveGeneric
  -   GADTs
  -   TypeFamilies
  -   MultiParamTypeClasses
  -   DeriveAnyClass
  -   DeriveFunctor
  -   GeneralizedNewtypeDeriving
  -   TypeOperators
  -   DefaultSignatures
  -   FlexibleContexts
